apiVersion: batch/v1
kind: Job
metadata:
  name: client-migrate-job
  namespace: apps
spec:
  template:
    spec:
      containers:
        - name: client-migrate-job
          image: ngoyarzo/nodejs-client:dev
          command: ["npx", "prisma", "migrate", "deploy", "--schema=prisma/schema/"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: client-db-url
                  key: DATABASE_URL
      restartPolicy: Never
  backoffLimit: 1
