apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-pvc-client
  labels:
    app: postgres-client
    tier: database
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 1Gi
