apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-region
  labels:
    app: nodejs-region
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-region
      tier: backend
  template:
    metadata:
      labels:
        app: nodejs-region
        tier: backend
    spec:
      containers:
        - name: nodejs-region
          image: ngoyarzo/nodejs-region:dev
          imagePullPolicy: Always
          ports:
             - containerPort: 3001
          env:
            - name: ACCEPTED_ORIGINS
              value: "*"
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: region-db-url
                  key: DATABASE_URL
          command: ["node", "src/server.js"]
          volumeMounts:
            - name: tls-certs
              mountPath: /certs
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: nodejs-region-tls
