apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-pvc
  labels:
    app: postgres
    tier: database
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 256Mi
