apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-react-ssr
  labels:
    app: nodejs-react-ssr
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-react-ssr
      tier: frontend
  template:
    metadata:
      labels:
        app: nodejs-react-ssr
        tier: frontend
    spec:
      containers:
        - name: nodejs-react-ssr
          image: ngoyarzo/nodejs-react-ssr:dev.12
          ports:
            - containerPort: 5173
          env:
            - name: NODE_ENV
              value: "production"
            - name: VITE_API_URL
              value: "https://nodejs-prisma-svc:3001/api"
            - name: API_URL
              value: "https://nodejs-prisma-svc:3001/api"
            - name: VITE_COMPANY_ID
              value: "0e9524f8-73f2-409c-8a1b-2aecda30d5f0"
          command: ["node", "server.js"]
