apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: web1
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`web1.labngo`)
      priority: 10
      services:
        - name: nginx-svc
          port: 80
  tls:
    certResolver: default
