apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web1-pvc
  namespace: default
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
