apiVersion: v1
kind: Service
metadata:
  name: nodejs-prisma-svc
  labels:
    app: nodejs
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: nodejs
    tier: backend
  ports:
    - port: 3000
      targetPort: 3000
