apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
      tier: backend
  template:
    metadata:
      labels:
        app: nodejs
        tier: backend
    spec:
      containers:
        - name: nodejs
          image: ngoyarzo/nodejs-prisma:4.0
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: prisma-db-url
                  key: DATABASE_URL
          command: ["sh", "-c"]
          args:
            - "npx prisma generate && 
              npx prisma migrate deploy && 
              node index.js"
          volumeMounts:
            - name: data
              mountPath: /app/node_modules  # Evita sobrescribir en bind mounts (solo desarrollo)
      volumes:
        - name: data
          emptyDir: {}  # Volumen temporal para node_modules
