apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
      tier: backend
  template:
    metadata:
      labels:
        app: nodejs
        tier: backend
    spec:
      containers:
        - name: nodejs
          image: ngoyarzo/nodejs-prisma:dev2.3
          ports:
            - containerPort: 3000
          env:
            - name: ACCEPTED_ORIGINS
              value: "*"
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: prisma-db-url
                  key: DATABASE_URL
          command: ["node", "src/server.js"]
