apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
      tier: backend
  template:
    metadata:
      labels:
        app: nodejs
        tier: backend
    spec:
      initContainers:
        # 0. InitContainer para prismac client
        - name: prisma-generate
          image: ngoyarzo/nodejs-prisma:7.0
          command: ["npx", "prisma", "generate"]
       # 1. InitContainer para migraciones
        - name: prisma-migrate
          image: ngoyarzo/nodejs-prisma:7.0
          command: ["npx", "prisma", "migrate", "deploy"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: prisma-db-url
                  key: DATABASE_URL
        # 2. InitContainer para seeds (ejecuta solo si las migraciones tienen éxito)
        - name: prisma-seed
          image: ngoyarzo/nodejs-prisma:7.0
          command: ["npx", "prisma", "db", "seed"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: prisma-db-url
                  key: DATABASE_URL
          # Opcional: Volumen para cache de Prisma (si el seed depende de archivos)
          volumeMounts:
            - mountPath: /app/node_modules/.prisma
              name: prisma-cache
      containers:
        - name: nodejs
          image: ngoyarzo/nodejs-prisma:7.0
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: prisma-db-url
                  key: DATABASE_URL
          command: ["node", "index.js"]
          #          args:
          #  - "npx prisma generate && 
          #    npx prisma migrate deploy && 
          #    node index.js"
          volumeMounts:
            - name: prisma-cache
              mountPath: /app/node_modules/.prisma
            - name: data
              mountPath: /app/node_modules  # Evita sobrescribir en bind mounts (solo desarrollo)
      volumes:
        - name: prisma-cache
          emptyDir: {}
        - name: data
          emptyDir: {}  # Volumen temporal para node_modules
