apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-prisma-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - nodejs-prisma.ngo.k3s.lab
      secretName: nodejs-prisma-tls
  rules:
    - host: nodejs-prisma.ngo.k3s.lab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nodejs-prisma-svc
                port:
                  number: 3001

