apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-seed-job
  namespace: apps
spec:
  template:
    spec:
      containers:
        - name: prisma-seed-job
          image: ngoyarzo/nodejs-prisma:dev
          command: ["node", "prisma/seed.js"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: prisma-db-url
                  key: DATABASE_URL
      restartPolicy: Never
  backoffLimit: 1
