apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate-job
  namespace: apps
spec:
  template:
    spec:
      containers:
        - name: prisma-migrate
          image: ngoyarzo/nodejs-prisma:34.0
          command: ["npx", "prisma", "migrate", "deploy"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: prisma-db-url
                  key: DATABASE_URL
      restartPolicy: Never
  backoffLimit: 1
