apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-seed-job
  namespace: apps
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: prisma-seed
          image: ngoyarzo/nodejs-prisma:34.0
          command: ["node", "prisma/seed.js"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: prisma-db-url
                  key: DATABASE_URL
      restartPolicy: Never
  backoffLimit: 1
