apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    tier: frontend
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      tier: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
          - containerPort: 80
        resources: {}
        volumeMounts:
#        - name: contents
#          mountPath: /var/www/html
#          readOnly: true
        - name: config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: default 
          mountPath: /etc/nginx/conf.d/defaul.conf
          subPath: default.conf
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: nginx-cm
      - name: default
        configMap:
          name: nginx-default-cm
#      - name: contents
#        persistentVolumeClaim:
#          claimName: nginx-pvc
status: {}
