apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    tier: frontend
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      tier: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: git-sync
        image: registry.k8s.io/git-sync/git-sync:v4.0.0
        args:
          - --repo=https://github.com/ngonet/html.git
          - --ref=main
          - --root=/git
        volumeMounts:
          - name: content-nginx
            mountPath: /git
      - image: nginx
        name: nginx
        ports:
          - containerPort: 80
        resources: {}
        volumeMounts:
        - name: content-nginx
          mountPath: /var/www/html
        - name: content-phpfpm
          mountPath: /var/www/html/phpfpm
        - name: config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: default 
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: true
        - name: conf-phpfpm
          mountPath: /etc/nginx/conf.d/phpfpm.conf
          subPath: phpfpm.conf
          readOnly: true
        - name: conf-www 
          mountPath: /etc/nginx/conf.d/www.conf
          subPath: www.conf
          readOnly: true
        - name: conf-notaria
          mountPath: /etc/nginx/conf.d/notaria.conf
          subPath: notaria.conf
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: cm-nginx
      - name: default
        configMap:
          name: cm-nginx-default
      - name: conf-phpfpm
        configMap:
          name: cm-nginx-phpfpm
      - name: conf-www
        configMap:
          name: cm-nginx-www
      - name: conf-notaria
        configMap:
          name: cm-nginx-notaria
      - name: content-phpfpm
        persistentVolumeClaim:
          claimName: phpfpm-pvc
      - name: content-nginx
        emptyDir: {}
status: {}
