apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    tier: frontend
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      tier: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
          - containerPort: 80
        resources: {}
        volumeMounts:
        - name: content-phpfpm
          mountPath: /var/www/html/phpfpm
          readOnly: true
#        - name: content-www
#          mountPath: /var/www/html/www
#          readOnly: true
        - name: config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: default 
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: true
        - name: conf-phpfpm
          mountPath: /etc/nginx/conf.d/phpfpm.conf
          subPath: phpfpm.conf
          readOnly: true
#        - name: conf-www 
#          mountPath: /etc/nginx/conf.d/www.conf
#          subPath: www.conf
#          readOnly: true
      volumes:
      - name: config
        configMap:
          name: cm-nginx
      - name: default
        configMap:
          name: cm-nginx-default
      - name: conf-phpfpm
        configMap:
          name: cm-nginx-phpfpm
#      - name: conf-www
#        configMap:
#          name: cm-nginx-www
      - name: content-phpfpm
        persistentVolumeClaim:
          claimName: phpfpm-pvc
#      - name: content-www
#        persistentVolumeClaim:
#          claimName: www-pvc
status: {}
