FROM node:20-alpine AS builder

WORKDIR /app

RUN apk add --no-cache openssl

COPY package.json package-lock.json* ./

RUN npm ci

COPY . .

FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=development

COPY --from=builder /app /app

EXPOSE 5173

CMD ["npm", "run", "dev"]
