apiVersion: v1
kind: Pod
metadata:
  name: nodejs-prisma-pod
  labels:
    app: nodejs-prisma
spec:
  containers:
    - name: nodejs
      image: ngoyarzo/nodejs-prisma:2.0
      env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: prisma-db-url
              key: DATABASE_URL
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: POSTGRES_PASSWORD
      volumeMounts:
        - name: data
          mountPath: /app/node_modules  # Evita sobrescribir en bind mounts (solo desarrollo)
  volumes:
    - name: data
      emptyDir: {}  # Volumen temporal para node_modules
