apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: phpfpm
    tier: backend
  name: phpfpm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: phpfpm
  strategy: {}
  template:
    metadata:
      labels:
        app: phpfpm
    spec:
      containers:
      - image: php:fpm-alpine
        name: phpfpm
        resources: {}
        volumeMounts:
        - name: contents
          mountPath: /var/www/html
          readOnly: true
      volumes:
      - name: contents
        persistentVolumeClaim:
          claimName: nginx-pvc
status: {}
