apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: phpfpm
  name: phpfpm-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: phpfpm
status:
  loadBalancer: {}
