apiVersion: v1
kind: Service
metadata:
  name: pgsql-region-svc
  labels:
    app: postgres-region
    tier: database
spec:
  type: ClusterIP
  selector:
    app: postgres-region
    tier: database
  ports:
    - port: 5432
      targetPort: 5432
